### ISSUE TITLE
Add support for SwerveModuleState

### ISSUE THREAD

**Issue by Gold872** [shueja/Monologue#3]
WPILib supports it as a struct, and it's incredibly useful to log

**Comment by oh-yes-0-fps** [comment]
Any object thats a struct can be logged automatically right now. The amount of work to add an exception for a specific object is not at all proportional to benefit and is awful for maintainability of code.

**Comment by Gold872** [comment]
Looking at the source code for the kinematics classes there is going to be support for SwerveModuleState, SwerveModulePosition, and a few other kinematics classes in the next release

**Comment by shueja** [comment]
Now that that beta has been released, we're planning on expanding logging support to any object that has a struct.
